import{a as b,S as w,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const v="50541308-8b3817b4b3c5c4721b4bd6fc3",S="https://pixabay.com/api/";async function u(s,t=1){const r={key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await b.get(S,{params:r})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250,captions:!1});function p(s){const t=s.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="info">
        <p>Likes: ${r.likes}</p>
        <p>Views: ${r.views}</p>
        <p>Comments: ${r.comments}</p>
        <p>Downloads: ${r.downloads}</p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function B(){f.innerHTML=""}function y(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function M(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}const $=document.querySelector(".form"),P=document.querySelector(".load-more");let i="",n=1,d=0;$.addEventListener("submit",async s=>{if(s.preventDefault(),i=s.target.elements["search-text"].value.trim(),!i){a.error({message:"Please enter a search term."});return}n=1,B(),L(),y();try{const t=await u(i,n);if(d=t.totalHits,t.hits.length===0){a.error({message:"Sorry, no images found. Try another search."});return}p(t.hits),d>15&&M()}catch{a.error({message:"An error occurred while fetching images."})}finally{g()}});P.addEventListener("click",async()=>{n+=1,y();try{const s=await u(i,n);p(s.hits);const t=Math.ceil(d/15);n>=t&&(L(),a.info({message:"We're sorry, but you've reached the end of search results."}));const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch{a.error({message:"Failed to load more images."})}finally{g()}});
//# sourceMappingURL=index.js.map
